<a href="https://colab.research.google.com/github/Arunachalam-J/machine_learning/blob/main/uci_malware_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import modules:
sklearn, pandas, numpy

In [ ]:
import sklearn

In [ ]:
from sklearn.metrics import precision_recall_fscore_support

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier

In [ ]:
import pandas as pd

In [ ]:
import os

In [ ]:
print(dir(RandomForestClassifier))
print(RandomForestClassifier())

['__abstractmethods__', '__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_check_feature_names', '_check_n_features', '_compute_oob_predictions', '_estimator_type', '_get_oob_predictions', '_get_param_names', '_get_tags', '_make_estimator', '_more_tags', '_parameter_constraints', '_repr_html_', '_repr_html_inner', '_repr_mimebundle_', '_required_parameters', '_set_oob_score_and_attributes', '_validate_X_predict', '_validate_data', '_validate_estimator', '_validate_params', '_validate_y_class_weight', 'apply', 'base_estimator_', 'decision_path', 'feature_importances_', 'fit', 'get_params', 'predic

In [ ]:
os.getcwd()

'/content'

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/uci_malware_detection.csv")
data.head()

Label  F_1  F_2  F_3  F_4  F_5  F_6  F_7  F_8  F_9  ...  F_522  \
0  non-malicious    1    0    1    0    1    0    1    0    1  ...      0   
1  non-malicious    1    0    1    0    1    0    1    0    1  ...      0   
2  non-malicious    1    0    1    0    1    0    1    0    1  ...      0   
3  non-malicious    1    0    1    0    1    0    1    0    1  ...      0   
4  non-malicious    1    0    1    0    1    0    1    0    1  ...      0   

   F_523  F_524  F_525  F_526  F_527  F_528  F_529  F_530  F_531  
0      0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0      0  

[5 rows x 532 columns]

In [ ]:
data.loc[:,data.columns!="Label"].head()

F_1  F_2  F_3  F_4  F_5  F_6  F_7  F_8  F_9  F_10  ...  F_522  F_523  \
0    1    0    1    0    1    0    1    0    1     0  ...      0      0   
1    1    0    1    0    1    0    1    0    1     0  ...      0      0   
2    1    0    1    0    1    0    1    0    1     0  ...      0      0   
3    1    0    1    0    1    0    1    0    1     0  ...      0      0   
4    1    0    1    0    1    0    1    0    1     0  ...      0      0   

   F_524  F_525  F_526  F_527  F_528  F_529  F_530  F_531  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 531 columns]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
    data.loc[:,data.columns!="Label"], data.loc[:,data.columns=="Label"], test_size=0.2
)
x_train

F_1  F_2  F_3  F_4  F_5  F_6  F_7  F_8  F_9  F_10  ...  F_522  F_523  \
282    1    0    1    0    1    0    1    0    1     0  ...      0      0   
220    1    0    1    0    1    0    1    0    1     0  ...      1      0   
126    1    0    1    0    1    0    1    0    1     0  ...      0      0   
21     1    0    1    0    1    0    1    0    1     0  ...      0      0   
341    1    0    1    0    1    0    1    0    1     0  ...      0      0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...    ...    ...   
66     1    0    1    0    1    0    1    0    1     0  ...      0      0   
261    1    0    1    0    1    0    1    0    1     0  ...      0      1   
46     1    0    1    0    1    0    1    0    1     0  ...      0      0   
291    1    0    1    0    1    0    1    0    1     0  ...      0      0   
212    1    0    1    0    1    0    1    0    1     0  ...      0      1   

     F_524  F_525  F_526  F_527  F_528  F_529  F_530  F_531  
282      0      0      0      0      0      0      0      1  
220      0      0      1      0      0      0      1      0  
126      0      0      1      0      0      0      1      0  
21       0      0      0      0      0      0      0      0  
341      0      0      0      1      0      0      0      0  
..     ...    ...    ...    ...    ...    ...    ...    ...  
66       0      0      0      0      0      0      0      0  
261      0      0      1      0      0      0      1      0  
46       0      0      0      0      0      0      0      0  
291      0      0      1      0      0      0      1      0  
212      0      0      0      0      0      0      1      0  

[298 rows x 531 columns]

In [ ]:
y_train

Label
282      malicious
220      malicious
126      malicious
21   non-malicious
341      malicious
..             ...
66   non-malicious
261      malicious
46   non-malicious
291      malicious
212      malicious

[298 rows x 1 columns]

In [ ]:
rf = RandomForestClassifier(n_jobs=-1)
rf.fit(x_train,y_train)

<ipython-input-24-5676d2d147dc>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(x_train,y_train)


RandomForestClassifier(n_jobs=-1)

In [ ]:
predicted = rf.predict(x_test)


Metrics collections and validation.

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
score = accuracy_score(y_test, predicted)
print(score)

0.9733333333333334


In [ ]:
print(dir(sklearn.metrics))

['ConfusionMatrixDisplay', 'DetCurveDisplay', 'DistanceMetric', 'PrecisionRecallDisplay', 'PredictionErrorDisplay', 'RocCurveDisplay', 'SCORERS', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_base', '_classification', '_dist_metrics', '_pairwise_distances_reduction', '_pairwise_fast', '_plot', '_ranking', '_regression', '_scorer', 'accuracy_score', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'auc', 'average_precision_score', 'balanced_accuracy_score', 'brier_score_loss', 'calinski_harabasz_score', 'check_scoring', 'class_likelihood_ratios', 'classification_report', 'cluster', 'cohen_kappa_score', 'completeness_score', 'confusion_matrix', 'consensus_score', 'coverage_error', 'd2_absolute_error_score', 'd2_pinball_score', 'd2_tweedie_score', 'davies_bouldin_score', 'dcg_score', 'det_curve', 'euclidean_distances', 'explained_variance_score', 'f1_score', 'fbeta_score', 'fowlkes_mallows_score', 'ge

In [ ]:
precision_recall_fscore_support(y_test, predicted)

(array([0.98412698, 0.91666667]),
 array([0.98412698, 0.91666667]),
 array([0.98412698, 0.91666667]),
 array([63, 12]))

In [ ]:
precision_recall_fscore_support(y_test, predicted,labels=["malicious"])

(array([0.98412698]), array([0.98412698]), array([0.98412698]), array([63]))